Repository DestinysCodePortfolio/FRAT-NIGHT, pull requests merged in 2025-05, with the labels that each got.

#9 Added the interface terminal
  CMakeLists.txt
  lib/interfaceTerminal.hpp
  main.cpp
  src/interfaceTerminal.cpp
  src/main.cpp
Labels: enhancement

#15 header file for the npcClass has been created
  header/npcClass.hpp
  lib/npcClass.cpp
Labels: enhancement, good first issue

#14 Adding the quickTimeEvent implementation ability
  quickTimeEvent.cpp
  quickTimeEvent.h
Labels: enhancement

#26 Started Scenes
  header/interfaceTerminal.hpp
  lib/CMakeLists.txt
  lib/interfaceTerminal.cpp
Labels: documentation

#21 Dialogue Tree testing
  CMakeLists.txt
  header/dialogueTree.hpp
  header/interfaceTerminal.hpp
  header/scene.hpp
  lib/CMakeLists.txt
  lib/interfaceTerminal.cpp
  lib/main.cpp
  lib/scene.cpp
Labels: bug, enhancement

#31 Setting up scene and dialogue tree
  header/npcClass.hpp
  header/player.hpp
  header/scene.hpp
  lib/npcClass.cpp
  lib/player.cpp
  lib/scene.cpp
Labels: bug, documentation

#39 Pchai010/cleaning files
  CMakeLists.txt
  header/DialogueTree.hpp
  header/SaveAndLoadData.hpp
  header/interfaceTerminal.hpp
  header/npcClass.hpp
  header/player.hpp
  header/quickTimeEvent.hpp
  header/scene.hpp
  lib/CMakeLists.txt
  lib/DialogueTree.cpp
  lib/SaveAndLoadData.cpp
  lib/interfaceTerminal.cpp
  lib/main.cpp
  lib/npcClass.cpp
  lib/player.cpp
  lib/scene.cpp
Labels: bug, documentation

#40 Update README.md
  README.md
Labels: documentation

#44 Implemented Dialogue Tree
  header/DialogueTree.hpp
  lib/DialogueTree.cpp
  lib/FRAT NIGHT SCRIPT.txt
Labels: documentation
